/**
 * Groth16 verifier for Spec B (SNARK-per-redeem).
 *
 * Verifies a snarkjs Groth16 proof on BN254 (alt_bn128). Public input layout
 * (4 elements) is locked in `circuits/redeem.circom`:
 *
 *   publicInputs[0] = root
 *   publicInputs[1] = nullifier
 *   publicInputs[2] = recipient
 *   publicInputs[3] = denomination
 *
 * Verifying-key bytes are generated by `circuits/scripts/gen-vk-bytes.mjs`
 * from `keys/vk_dev.json`. Production ceremony swaps in a new vk file; this
 * verifier is vk-agnostic — only the imported `snark_vk_*.algo.ts` module
 * needs to be regenerated.
 *
 * Wire encoding (AVM EC opcodes, BN254):
 *   G1 point   = X(32B) || Y(32B)             — 64 bytes
 *   G2 point   = X0(32B) || X1(32B) || Y0(32B) || Y1(32B)   — 128 bytes
 *   Scalar     = 32-byte big-endian
 *   Proof blob = A(G1, 64B) || B(G2, 128B) || C(G1, 64B)    — 256 bytes
 *
 * Groth16 verify check:
 *   e(-A, B) · e(α, β) · e(vk_x, γ) · e(C, δ) == 1
 * where vk_x = IC[0] + Σ IC[i+1] * pub[i].
 *
 * BN254 Fq prime modulus (NOT Fr):
 *   Q = 21888242871839275222246405745257275088696311157297823662689037894645226208583
 */

import {
  assert,
  BigUint,
  Bytes,
  op,
  ensureBudget,
  OpUpFeeSource,
} from "@algorandfoundation/algorand-typescript";
import type {
  bytes,
  biguint,
  uint64,
} from "@algorandfoundation/algorand-typescript";

import {
  VK_ALPHA_1,
  VK_BETA_2,
  VK_GAMMA_2,
  VK_DELTA_2,
  VK_IC_0,
  VK_IC_1,
  VK_IC_2,
  VK_IC_3,
  VK_IC_4,
  VK_NPUBLIC,
} from "./snark_vk_mimc_dev.algo";

// BN254 Fq (base field) modulus.
const FQ_MOD: biguint = BigUint(
  Bytes.fromHex(
    "30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47",
  ),
);

const ZERO_32: bytes = Bytes.fromHex(
  "0000000000000000000000000000000000000000000000000000000000000000",
);

export const PROOF_BYTES: uint64 = 256;
export const G1_BYTES: uint64 = 64;
export const G2_BYTES: uint64 = 128;
export const SCALAR_BYTES: uint64 = 32;

/**
 * Negate a G1 point: (x, y) → (x, q - y), with (x, 0) fixed (point at infinity
 * has y = 0; negation is identity).
 */
function negG1(p: bytes): bytes {
  assert(p.length === G1_BYTES, "BAD_G1_LEN");
  const x = p.slice(0, 32);
  const y = p.slice(32, 64);
  if (y.equals(ZERO_32)) return p;
  // negY = (q - y). Since 0 < y < q, plain subtraction stays in field.
  const negY: biguint = BigUint(FQ_MOD - BigUint(y));
  const negYBytes: bytes = Bytes(negY);
  return x.concat(padLeft32(negYBytes));
}

function padLeft32(b: bytes): bytes {
  if (b.length === 32) return b;
  assert(b.length < 32, "OVERFLOW_32");
  return op.bzero(32 - b.length).concat(b);
}

/**
 * Compute vk_x = IC[0] + Σ IC[i+1] * publicInputs[i].
 *
 * `publicInputs` must be a single contiguous buffer of `VK_NPUBLIC * 32`
 * bytes, each input a big-endian 32-byte scalar.
 */
function accumulateVkX(publicInputs: bytes): bytes {
  assert(
    publicInputs.length === (VK_NPUBLIC as uint64) * (SCALAR_BYTES as uint64),
    "BAD_PUB_LEN",
  );

  // Start with IC[0].
  let acc = VK_IC_0;

  // Unrolled: nPublic = 4. If circuit changes, regenerate vk + extend here.
  const s0 = publicInputs.slice(0, 32);
  const s1 = publicInputs.slice(32, 64);
  const s2 = publicInputs.slice(64, 96);
  const s3 = publicInputs.slice(96, 128);

  const t0 = op.EllipticCurve.scalarMul(op.Ec.BN254g1, VK_IC_1, s0);
  acc = op.EllipticCurve.add(op.Ec.BN254g1, acc, t0);

  const t1 = op.EllipticCurve.scalarMul(op.Ec.BN254g1, VK_IC_2, s1);
  acc = op.EllipticCurve.add(op.Ec.BN254g1, acc, t1);

  const t2 = op.EllipticCurve.scalarMul(op.Ec.BN254g1, VK_IC_3, s2);
  acc = op.EllipticCurve.add(op.Ec.BN254g1, acc, t2);

  const t3 = op.EllipticCurve.scalarMul(op.Ec.BN254g1, VK_IC_4, s3);
  acc = op.EllipticCurve.add(op.Ec.BN254g1, acc, t3);

  return acc;
}

/**
 * Verify a Groth16 proof against the embedded vk + supplied public inputs.
 *
 *   proof          — 256-byte concat of (A_G1 || B_G2 || C_G1)
 *   publicInputs   — 4*32 = 128-byte concat of public scalars
 *
 * Returns true if the proof verifies, false otherwise. Reverts on malformed
 * input lengths so the caller doesn't accept a false negative due to encoding
 * bugs.
 *
 * NB: the caller is responsible for pooling opcode budget — verify is
 * expensive (≈ 6 scalarMuls + 4 G1 adds + 1 pairing). Use
 * `ensureSnarkBudget()` immediately before calling.
 */
export function verifyGroth16(proof: bytes, publicInputs: bytes): boolean {
  assert(proof.length === PROOF_BYTES, "BAD_PROOF_LEN");

  const aRaw = proof.slice(0, 64);
  const b = proof.slice(64, 192);
  const c = proof.slice(192, 256);

  // Compute vk_x.
  const vkX = accumulateVkX(publicInputs);

  // Build the 4-pair pairing check buffers.
  //   g1_list = [-A, alpha, vk_x, C]
  //   g2_list = [ B, beta,  gamma, delta]
  const negA = negG1(aRaw);
  const g1List = negA.concat(VK_ALPHA_1).concat(vkX).concat(c);
  const g2List = b.concat(VK_BETA_2).concat(VK_GAMMA_2).concat(VK_DELTA_2);

  assert(g1List.length === 4 * (G1_BYTES as uint64), "G1_LIST_LEN");
  assert(g2List.length === 4 * (G2_BYTES as uint64), "G2_LIST_LEN");

  return op.EllipticCurve.pairingCheck(op.Ec.BN254g1, g1List, g2List);
}

/**
 * Pool enough opcode budget for one `verifyGroth16` call.
 *
 * Measured on LocalNet against vector-01-basic (DEV vk, nPublic=4):
 *   - 60 000 units → insufficient
 *   - 80 000 units → passes (positive + tampered cases)
 *   Pool cost dominated by 4× ec_scalar_mul + 1× ec_pairing_check.
 *
 * We pool 80k with a comfortable head-room margin to absorb fluctuations from
 * future EC opcode reprices. Each OpUp inner txn raises the budget by 700
 * units; 80k ÷ 700 ≈ 115 inner txns, well below the 256 inner-txn ceiling.
 *
 * Callers must supply enough static fee to cover those inner txns
 * (≈ 200 000 µAlgo for the current pool size — each OpUp pays minTxnFee).
 */
export function ensureSnarkBudget(): void {
  ensureBudget(80000, OpUpFeeSource.GroupCredit);
}
