import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:sealed_app/features/wallet/credits_service.dart';

class _FakeOps implements SealedCreditOps {
  int balance = 0;
  Uint8List? lastPreimage;
  String? lastUsername;
  String? lastFrom;

  @override
  Future<int> getCredits(String walletAddress) async => balance;

  @override
  Future<int> refetchCredits(String walletAddress) async => balance;

  @override
  Future<String> redeem({
    required Uint8List preimage,
    required String username,
    required String fromAddress,
  }) async {
    lastPreimage = preimage;
    lastUsername = username;
    lastFrom = fromAddress;
    return 'TXID_REDEEM_${preimage.first.toRadixString(16)}';
  }

  @override
  Future<String> redeemWithProof({
    required Uint8List rootRef,
    required Uint8List nullifier,
    required Uint8List proof,
    required Uint8List pubInputs,
    required String fromAddress,
    String? username,
  }) async {
    throw UnimplementedError();
  }

  @override
  Future<String> redeemWithProofAndPublishKeys({
    required Uint8List rootRef,
    required Uint8List nullifier,
    required Uint8List proof,
    required Uint8List pubInputs,
    required String fromAddress,
    required Uint8List encryptionPubkey,
    required Uint8List scanPubkey,
    required Uint8List pqPubkey,
  }) async {
    throw UnimplementedError();
  }

  @override
  Future<bool> rootBoxExists(Uint8List rootRef) async => true;
}

String _hex(Uint8List b) =>
    b.map((e) => e.toRadixString(16).padLeft(2, '0')).join();

void main() {
  group('CreditsService — code normalization (parity with TS contract)', () {
    test('normalizeCode: dashes/spaces stripped, lowercase upper-cased', () {
      expect(
        CreditsService.normalizeCode('abcd-efgh-jkmn-pqrs'),
        'ABCDEFGHJKMNPQRS',
      );
      expect(
        CreditsService.normalizeCode(' 1234 5678 90AB CDEF '),
        '1234567890ABCDEF',
      );
    });

    test('normalizeCode: I→1, L→1, O→0', () {
      // "I0L1O" → "10110" — 5 chars. Pad with 11 valid alphabet chars to reach 16.
      expect(
        CreditsService.normalizeCode('I0L1O23456789ABC'),
        '1011023456789ABC',
      );
    });

    test('normalizeCode: throws on wrong length', () {
      expect(
        () => CreditsService.normalizeCode('ABCD'),
        throwsA(isA<CreditsServiceException>()),
      );
      expect(
        () => CreditsService.normalizeCode('A' * 17),
        throwsA(isA<CreditsServiceException>()),
      );
    });

    test('normalizeCode: throws on chars outside Crockford', () {
      // 'U' is excluded from the alphabet.
      expect(
        () => CreditsService.normalizeCode('U234567890ABCDEF'),
        throwsA(isA<CreditsServiceException>()),
      );
    });

    test('formatCode: groups into 4-char chunks with dashes', () {
      expect(
        CreditsService.formatCode('1234567890ABCDEF'),
        '1234-5678-90AB-CDEF',
      );
    });
  });

  group(
    'CreditsService — golden vectors (must match TS contract `code.ts`)',
    () {
      // Generated by:
      //   node -e "..." against programs/sealed/src/lib/code.ts logic.
      test('preimage/commitment for ABCD-EFGH-JKMN-PQRS', () {
        final pre = CreditsService.preimageFromCode('ABCD-EFGH-JKMN-PQRS');
        expect(_hex(pre), 'f598056127fcd4387651a49b3a4235d8');
        final com = CreditsService.commitmentFromCode('ABCD-EFGH-JKMN-PQRS');
        expect(
          _hex(com),
          '79c6ec134a34d44d28e24a69a4c826ac8eae49f59c3cbacfd5b4091ab445f31f',
        );
      });

      test('preimage/commitment for 0000-0000-0000-0000', () {
        final pre = CreditsService.preimageFromCode('0000-0000-0000-0000');
        expect(_hex(pre), 'fcdb4b423f4e5283afa249d762ef6aef');
        final com = CreditsService.commitmentFromCode('0000-0000-0000-0000');
        expect(
          _hex(com),
          '47bd7c5ca682ff7fa16dcdc982f8f263184fe7edd1c34183ce3c0cac4b91ccdf',
        );
      });

      test('preimage/commitment for 1234-5678-90AB-CDEF', () {
        final pre = CreditsService.preimageFromCode('1234567890ABCDEF');
        expect(_hex(pre), '0b3e4e625d89234675099ff36b5b5b8f');
        final com = CreditsService.commitmentFromCode('1234567890ABCDEF');
        expect(
          _hex(com),
          '9aa5a40378fb1c72d3925499c321d7b0bfff4327d4dfc85c46bf4a1ffa98e779',
        );
      });
    },
  );

  group('CreditsService — API', () {
    test('getCredits delegates to ops', () async {
      final ops = _FakeOps()..balance = 42;
      final svc = CreditsService(ops);
      expect(await svc.getCredits('ADDR'), 42);
    });

    test('redeem passes derived preimage + username + from to ops', () async {
      final ops = _FakeOps();
      final svc = CreditsService(ops);
      final txid = await svc.redeem(
        code: '1234-5678-90AB-CDEF',
        username: 'alice',
        fromAddress: 'WALLET',
      );
      expect(txid, startsWith('TXID_REDEEM_'));
      expect(_hex(ops.lastPreimage!), '0b3e4e625d89234675099ff36b5b5b8f');
      expect(ops.lastUsername, 'alice');
      expect(ops.lastFrom, 'WALLET');
    });

    test('redeem with empty username defaults to no claim', () async {
      final ops = _FakeOps();
      final svc = CreditsService(ops);
      await svc.redeem(code: '1234567890ABCDEF', fromAddress: 'W');
      expect(ops.lastUsername, '');
    });

    test('redeem throws on bad code without calling ops', () async {
      final ops = _FakeOps();
      final svc = CreditsService(ops);
      await expectLater(
        svc.redeem(code: 'too-short', fromAddress: 'W'),
        throwsA(isA<CreditsServiceException>()),
      );
      expect(ops.lastPreimage, isNull);
    });
  });
}
