import 'package:flutter/material.dart';
import 'package:flutter_gap/flutter_gap.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:sealed_app/ui/chat/widgets/alias_invitation.dart';
import 'package:sealed_app/ui/chats/screens/alias/generate.dart';
import 'package:sealed_app/ui/chats/screens/alias/scan.dart';
import 'package:sealed_app/ui/shared/widgets/action_tile.dart';
import 'package:sealed_app/ui/shared/widgets/sealed_layout.dart';
import 'package:sealed_app/ui/shared/widgets/topbar.dart';

class OfflineConnectionScreen extends StatelessWidget {
  const OfflineConnectionScreen({super.key});

  void _push(BuildContext context, Widget screen) {
    Navigator.of(context).push(MaterialPageRoute(builder: (_) => screen));
  }

  @override
  Widget build(BuildContext context) {
    return SealedLayout(
      topBar: TopBar(label: "Offline connection"),
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        ActionTile(
          label: "Scan Key",
          subtitle: "Scan the code generated by the other person",
          assetPath: "assets/svg/chats/qr.svg",
          onTap: () => _push(context, const ScanKeyScreen()),
        ),
        Gap(12.h),
        ActionTile(
          label: "Generate Key",
          subtitle: "Generate a code for the other person",
          assetPath: "assets/svg/key.svg",
          onTap: () => _push(context, const GenerateKeyScreen()),
        ),
        Gap(16.h),
        Text(
          'Chat Alias allows you to create a private alias for this conversation. Your identity remains hidden while you communicate securely.',
          style: Theme.of(context).textTheme.bodyMedium,
        ),
        Gap(24.h),
        FeatureRow(
          iconAsset: 'assets/svg/contact_profile/shield.svg',
          title: "Protect your identity",
          subtitle: "wallet address and personal identity hidden",
        ),
        Gap(24.h),
        FeatureRow(
          iconAsset: 'assets/svg/contact_profile/eye.svg',
          title: "Communicate privately",
          subtitle: "exchange messages without exposing",
        ),
        Gap(24.h),
        FeatureRow(
          iconAsset: 'assets/svg/contact_profile/close.svg',
          title: "Alias can be revoked forever",
          subtitle: "full control by removing the connection",
        ),
      ],
    );
  }
}
